name: coin-integration-alpha
on:
  push:
    branches:
      - 'int-*'
jobs:
  prebuild-for-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-2016]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
      - uses: actions/setup-python@v1
        with:
          python-version: '2.7.x'
      - name: extract coin name
        run: |
            COIN=$(./extract-coin-name.sh)
      - name: install
        run: yarn --frozen-lockfile --ignore-scripts
      - name: config gcc
        if: runner.os == 'Linux'
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
      - name: prebuild for node 6
        run: npx node-pre-gyp configure build package --target=6.17.1
      - name: Get version and publish @coin on NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GAGBO_PUBLISH_TOKEN }}
        run: |
            yarn version --prerelease --preid "$COIN"
            yarn publish --tag "$COIN"
