name: coin-integration-alpha
defaults:
  run:
    working-directory: goingnative-addon
on:
  push:
    branches:
      - 'int-*'
jobs:
  prebuild-for-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 6.x
          always-auth: true
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_GAGBO_PUBLISH_TOKEN }}" > ~/.npmrc
      - uses: actions/setup-python@v1
        with:
          python-version: '2.7.x'
      - name: install
        run: yarn --frozen-lockfile --ignore-scripts
      - name: config gcc
        if: runner.os == 'Linux'
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
      - name: prebuild for node 6
        run: npx node-pre-gyp configure build package --target=6.17.1
      - name: Extract coin name
        run: echo "##[set-output name=coin;]$(echo ${GITHUB_REF})"
        id: extract_coin
      - name: Get version and publish @coin on NPM
        if: matrix.os == 'ubuntu-18.04'
        run: |
            echo "I hope you remembered to run 'yarn version --prerelease --preid \"$COIN\"'"
            yarn publish --tag "$COIN"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GAGBO_PUBLISH_TOKEN }}
          COIN: ${{ steps.extract_coin.output.coin }}
